/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.guickie;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.guickie.Container#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.guickie.Container#getAlign <em>Align</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.guickie.Container#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.guickie.GuickiePackage#getContainer()
 * @model
 * @generated
 */
public interface Container extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.guickie.GuickiePackage#getContainer_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.guickie.Container#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Align</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Align</em>' containment reference.
   * @see #setAlign(EObject)
   * @see org.xtext.example.mydsl.guickie.GuickiePackage#getContainer_Align()
   * @model containment="true"
   * @generated
   */
  EObject getAlign();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.guickie.Container#getAlign <em>Align</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Align</em>' containment reference.
   * @see #getAlign()
   * @generated
   */
  void setAlign(EObject value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.guickie.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.xtext.example.mydsl.guickie.GuickiePackage#getContainer_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // Container
