/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.guickie;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GUI</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.guickie.GUI#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.guickie.GUI#getStyle <em>Style</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.guickie.GUI#getContainers <em>Containers</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.guickie.GuickiePackage#getGUI()
 * @model
 * @generated
 */
public interface GUI extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.xtext.example.mydsl.guickie.GuickiePackage#getGUI_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.guickie.GUI#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Style</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Style</em>' containment reference.
   * @see #setStyle(Style)
   * @see org.xtext.example.mydsl.guickie.GuickiePackage#getGUI_Style()
   * @model containment="true"
   * @generated
   */
  Style getStyle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.guickie.GUI#getStyle <em>Style</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Style</em>' containment reference.
   * @see #getStyle()
   * @generated
   */
  void setStyle(Style value);

  /**
   * Returns the value of the '<em><b>Containers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.guickie.Container}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Containers</em>' containment reference list.
   * @see org.xtext.example.mydsl.guickie.GuickiePackage#getGUI_Containers()
   * @model containment="true"
   * @generated
   */
  EList<Container> getContainers();

} // GUI
