/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.guickie;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.guickie.GuickieFactory
 * @model kind="package"
 * @generated
 */
public interface GuickiePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "guickie";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Guickie";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "guickie";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GuickiePackage eINSTANCE = org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.GUIImpl <em>GUI</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.GUIImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getGUI()
   * @generated
   */
  int GUI = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI__TITLE = 0;

  /**
   * The feature id for the '<em><b>Style</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI__STYLE = 1;

  /**
   * The feature id for the '<em><b>Containers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI__CONTAINERS = 2;

  /**
   * The number of structural features of the '<em>GUI</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.ContainerImpl <em>Container</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.ContainerImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getContainer()
   * @generated
   */
  int CONTAINER = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__NAME = 0;

  /**
   * The feature id for the '<em><b>Align</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__ALIGN = 1;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__ELEMENTS = 2;

  /**
   * The number of structural features of the '<em>Container</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.HorizontalImpl <em>Horizontal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.HorizontalImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getHorizontal()
   * @generated
   */
  int HORIZONTAL = 2;

  /**
   * The number of structural features of the '<em>Horizontal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.VerticalImpl <em>Vertical</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.VerticalImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getVertical()
   * @generated
   */
  int VERTICAL = 3;

  /**
   * The number of structural features of the '<em>Vertical</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.StyleImpl <em>Style</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.StyleImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getStyle()
   * @generated
   */
  int STYLE = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Style</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.NeonImpl <em>Neon</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.NeonImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getNeon()
   * @generated
   */
  int NEON = 5;

  /**
   * The number of structural features of the '<em>Neon</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEON_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.GreyImpl <em>Grey</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.GreyImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getGrey()
   * @generated
   */
  int GREY = 6;

  /**
   * The number of structural features of the '<em>Grey</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREY_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.ElementImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__TYPE = 1;

  /**
   * The feature id for the '<em><b>Link</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__LINK = 2;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.ButtonImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getButton()
   * @generated
   */
  int BUTTON = 8;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.LabelImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getLabel()
   * @generated
   */
  int LABEL = 9;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.TextFieldImpl <em>Text Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.TextFieldImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getTextField()
   * @generated
   */
  int TEXT_FIELD = 10;

  /**
   * The number of structural features of the '<em>Text Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FIELD_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.guickie.impl.HyperLinkImpl <em>Hyper Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.guickie.impl.HyperLinkImpl
   * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getHyperLink()
   * @generated
   */
  int HYPER_LINK = 11;

  /**
   * The number of structural features of the '<em>Hyper Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HYPER_LINK_FEATURE_COUNT = 0;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.GUI <em>GUI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GUI</em>'.
   * @see org.xtext.example.mydsl.guickie.GUI
   * @generated
   */
  EClass getGUI();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.guickie.GUI#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.xtext.example.mydsl.guickie.GUI#getTitle()
   * @see #getGUI()
   * @generated
   */
  EAttribute getGUI_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.guickie.GUI#getStyle <em>Style</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Style</em>'.
   * @see org.xtext.example.mydsl.guickie.GUI#getStyle()
   * @see #getGUI()
   * @generated
   */
  EReference getGUI_Style();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.guickie.GUI#getContainers <em>Containers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Containers</em>'.
   * @see org.xtext.example.mydsl.guickie.GUI#getContainers()
   * @see #getGUI()
   * @generated
   */
  EReference getGUI_Containers();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.Container <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container</em>'.
   * @see org.xtext.example.mydsl.guickie.Container
   * @generated
   */
  EClass getContainer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.guickie.Container#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.guickie.Container#getName()
   * @see #getContainer()
   * @generated
   */
  EAttribute getContainer_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.guickie.Container#getAlign <em>Align</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Align</em>'.
   * @see org.xtext.example.mydsl.guickie.Container#getAlign()
   * @see #getContainer()
   * @generated
   */
  EReference getContainer_Align();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.guickie.Container#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.guickie.Container#getElements()
   * @see #getContainer()
   * @generated
   */
  EReference getContainer_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.Horizontal <em>Horizontal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Horizontal</em>'.
   * @see org.xtext.example.mydsl.guickie.Horizontal
   * @generated
   */
  EClass getHorizontal();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.Vertical <em>Vertical</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertical</em>'.
   * @see org.xtext.example.mydsl.guickie.Vertical
   * @generated
   */
  EClass getVertical();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.Style <em>Style</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Style</em>'.
   * @see org.xtext.example.mydsl.guickie.Style
   * @generated
   */
  EClass getStyle();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.guickie.Style#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.guickie.Style#getType()
   * @see #getStyle()
   * @generated
   */
  EReference getStyle_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.Neon <em>Neon</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Neon</em>'.
   * @see org.xtext.example.mydsl.guickie.Neon
   * @generated
   */
  EClass getNeon();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.Grey <em>Grey</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grey</em>'.
   * @see org.xtext.example.mydsl.guickie.Grey
   * @generated
   */
  EClass getGrey();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.mydsl.guickie.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.guickie.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.guickie.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.guickie.Element#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.guickie.Element#getType()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Type();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.guickie.Element#getLink <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Link</em>'.
   * @see org.xtext.example.mydsl.guickie.Element#getLink()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Link();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.xtext.example.mydsl.guickie.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see org.xtext.example.mydsl.guickie.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.TextField <em>Text Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Field</em>'.
   * @see org.xtext.example.mydsl.guickie.TextField
   * @generated
   */
  EClass getTextField();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.guickie.HyperLink <em>Hyper Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hyper Link</em>'.
   * @see org.xtext.example.mydsl.guickie.HyperLink
   * @generated
   */
  EClass getHyperLink();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GuickieFactory getGuickieFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.GUIImpl <em>GUI</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.GUIImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getGUI()
     * @generated
     */
    EClass GUI = eINSTANCE.getGUI();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUI__TITLE = eINSTANCE.getGUI_Title();

    /**
     * The meta object literal for the '<em><b>Style</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GUI__STYLE = eINSTANCE.getGUI_Style();

    /**
     * The meta object literal for the '<em><b>Containers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GUI__CONTAINERS = eINSTANCE.getGUI_Containers();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.ContainerImpl <em>Container</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.ContainerImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getContainer()
     * @generated
     */
    EClass CONTAINER = eINSTANCE.getContainer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINER__NAME = eINSTANCE.getContainer_Name();

    /**
     * The meta object literal for the '<em><b>Align</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINER__ALIGN = eINSTANCE.getContainer_Align();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINER__ELEMENTS = eINSTANCE.getContainer_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.HorizontalImpl <em>Horizontal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.HorizontalImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getHorizontal()
     * @generated
     */
    EClass HORIZONTAL = eINSTANCE.getHorizontal();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.VerticalImpl <em>Vertical</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.VerticalImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getVertical()
     * @generated
     */
    EClass VERTICAL = eINSTANCE.getVertical();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.StyleImpl <em>Style</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.StyleImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getStyle()
     * @generated
     */
    EClass STYLE = eINSTANCE.getStyle();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STYLE__TYPE = eINSTANCE.getStyle_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.NeonImpl <em>Neon</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.NeonImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getNeon()
     * @generated
     */
    EClass NEON = eINSTANCE.getNeon();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.GreyImpl <em>Grey</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.GreyImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getGrey()
     * @generated
     */
    EClass GREY = eINSTANCE.getGrey();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.ElementImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__TYPE = eINSTANCE.getElement_Type();

    /**
     * The meta object literal for the '<em><b>Link</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__LINK = eINSTANCE.getElement_Link();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.ButtonImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.LabelImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.TextFieldImpl <em>Text Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.TextFieldImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getTextField()
     * @generated
     */
    EClass TEXT_FIELD = eINSTANCE.getTextField();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.guickie.impl.HyperLinkImpl <em>Hyper Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.guickie.impl.HyperLinkImpl
     * @see org.xtext.example.mydsl.guickie.impl.GuickiePackageImpl#getHyperLink()
     * @generated
     */
    EClass HYPER_LINK = eINSTANCE.getHyperLink();

  }

} //GuickiePackage
