/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.guickie;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text Field</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.guickie.GuickiePackage#getTextField()
 * @model
 * @generated
 */
public interface TextField extends EObject
{
} // TextField
