/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.AbstractGuickieRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GuickieRuntimeModule extends AbstractGuickieRuntimeModule {
}
