/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.GuickieStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GuickieStandaloneSetup extends GuickieStandaloneSetupGenerated {
  public static void doSetup() {
    new GuickieStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
