/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.guickie.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.guickie.Grey;
import org.xtext.example.mydsl.guickie.GuickiePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Grey</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GreyImpl extends MinimalEObjectImpl.Container implements Grey
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GreyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GuickiePackage.Literals.GREY;
  }

} //GreyImpl
