/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.guickie.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.guickie.GuickiePackage;
import org.xtext.example.mydsl.guickie.HyperLink;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hyper Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HyperLinkImpl extends MinimalEObjectImpl.Container implements HyperLink
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HyperLinkImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GuickiePackage.Literals.HYPER_LINK;
  }

} //HyperLinkImpl
