/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalGuickieParser;
import org.xtext.example.mydsl.services.GuickieGrammarAccess;

public class GuickieParser extends AbstractAntlrParser {

	@Inject
	private GuickieGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGuickieParser createParser(XtextTokenStream stream) {
		return new InternalGuickieParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GUI";
	}

	public GuickieGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GuickieGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
