/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.validation;

import org.xtext.example.mydsl.validation.AbstractGuickieValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GuickieValidator extends AbstractGuickieValidator {
}
